kind: Service
apiVersion: v1
metadata:
  name: mybot-fulfillment-service
spec:
  selector:
    app: mybot-fulfillment
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mybot-fulfillment
  labels:
    app: mybot-fulfillment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mybot-fulfillment
  template:
    metadata:
      labels:
        app: mybot-fulfillment
    spec:
      containers:
      - name:  mybot-fulfillment
        image: sorbra/dfdemo:1.0
        imagePullPolicy: Always
